version: '3.1'
services:
    mongo:
        image: mongo
        container_name: esgi-node-mongo
        ports:
            - 127.0.0.1:27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}

    server:
        build: './server'
        container_name: esgi-node-node
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - ./server:/app/server
        working_dir: /app/server
        command: 'npm start'
        depends_on:
            - mongo
        environment:
            MONGODB_USER: ${MONGODB_USER}
            MONGODB_PASS: ${MONGODB_PASS}
            MONGODB_NAME: ${MONGODB_NAME}
            JWT_SECRET: ${JWT_SECRET}

    client:
        build: './client'
        container_name: jai_mis_un_nom_pour_francois
        volumes:
            - ./client:/app/client
        working_dir: '/app/client'
        command: 'npm start'
        ports:
            - 127.00.1:3001:3000
